<?php
/**
 * ConversionsApi
 * PHP version 5
 *
 * @category Class
 * @package  LeadspediaApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * LeadsPedia API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.10
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace LeadspediaApi\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use LeadspediaApi\ApiException;
use LeadspediaApi\Configuration;
use LeadspediaApi\HeaderSelector;
use LeadspediaApi\ObjectSerializer;

/**
 * ConversionsApi Class Doc Comment
 *
 * @category Class
 * @package  LeadspediaApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ConversionsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation conversionsgetAlldo
     *
     * Get All
     *
     * @param  \DateTime $from_date from_date (required)
     * @param  int $vertical_id vertical_id (optional)
     * @param  int $offer_id offer_id (optional)
     * @param  int $affiliate_id affiliate_id (optional)
     * @param  int $campaign_id campaign_id (optional)
     * @param  int $advertiser_id advertiser_id (optional)
     * @param  string $status status (optional)
     * @param  string $show_goal show_goal (optional)
     * @param  string $show_non_goal show_non_goal (optional)
     * @param  string $show_throttled show_throttled (optional)
     * @param  string $show_non_throttled show_non_throttled (optional)
     * @param  string $show_test show_test (optional)
     * @param  string $show_non_test show_non_test (optional)
     * @param  \DateTime $to_date to_date (optional)
     * @param  int $start start (optional)
     * @param  int $limit limit (optional)
     *
     * @throws \LeadspediaApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function conversionsgetAlldo($from_date, $vertical_id = null, $offer_id = null, $affiliate_id = null, $campaign_id = null, $advertiser_id = null, $status = null, $show_goal = null, $show_non_goal = null, $show_throttled = null, $show_non_throttled = null, $show_test = null, $show_non_test = null, $to_date = null, $start = null, $limit = null)
    {
        $this->conversionsgetAlldoWithHttpInfo($from_date, $vertical_id, $offer_id, $affiliate_id, $campaign_id, $advertiser_id, $status, $show_goal, $show_non_goal, $show_throttled, $show_non_throttled, $show_test, $show_non_test, $to_date, $start, $limit);
    }

    /**
     * Operation conversionsgetAlldoWithHttpInfo
     *
     * Get All
     *
     * @param  \DateTime $from_date (required)
     * @param  int $vertical_id (optional)
     * @param  int $offer_id (optional)
     * @param  int $affiliate_id (optional)
     * @param  int $campaign_id (optional)
     * @param  int $advertiser_id (optional)
     * @param  string $status (optional)
     * @param  string $show_goal (optional)
     * @param  string $show_non_goal (optional)
     * @param  string $show_throttled (optional)
     * @param  string $show_non_throttled (optional)
     * @param  string $show_test (optional)
     * @param  string $show_non_test (optional)
     * @param  \DateTime $to_date (optional)
     * @param  int $start (optional)
     * @param  int $limit (optional)
     *
     * @throws \LeadspediaApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function conversionsgetAlldoWithHttpInfo($from_date, $vertical_id = null, $offer_id = null, $affiliate_id = null, $campaign_id = null, $advertiser_id = null, $status = null, $show_goal = null, $show_non_goal = null, $show_throttled = null, $show_non_throttled = null, $show_test = null, $show_non_test = null, $to_date = null, $start = null, $limit = null)
    {
        $returnType = '';
        $request = $this->conversionsgetAlldoRequest($from_date, $vertical_id, $offer_id, $affiliate_id, $campaign_id, $advertiser_id, $status, $show_goal, $show_non_goal, $show_throttled, $show_non_throttled, $show_test, $show_non_test, $to_date, $start, $limit);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation conversionsgetAlldoAsync
     *
     * Get All
     *
     * @param  \DateTime $from_date (required)
     * @param  int $vertical_id (optional)
     * @param  int $offer_id (optional)
     * @param  int $affiliate_id (optional)
     * @param  int $campaign_id (optional)
     * @param  int $advertiser_id (optional)
     * @param  string $status (optional)
     * @param  string $show_goal (optional)
     * @param  string $show_non_goal (optional)
     * @param  string $show_throttled (optional)
     * @param  string $show_non_throttled (optional)
     * @param  string $show_test (optional)
     * @param  string $show_non_test (optional)
     * @param  \DateTime $to_date (optional)
     * @param  int $start (optional)
     * @param  int $limit (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function conversionsgetAlldoAsync($from_date, $vertical_id = null, $offer_id = null, $affiliate_id = null, $campaign_id = null, $advertiser_id = null, $status = null, $show_goal = null, $show_non_goal = null, $show_throttled = null, $show_non_throttled = null, $show_test = null, $show_non_test = null, $to_date = null, $start = null, $limit = null)
    {
        return $this->conversionsgetAlldoAsyncWithHttpInfo($from_date, $vertical_id, $offer_id, $affiliate_id, $campaign_id, $advertiser_id, $status, $show_goal, $show_non_goal, $show_throttled, $show_non_throttled, $show_test, $show_non_test, $to_date, $start, $limit)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation conversionsgetAlldoAsyncWithHttpInfo
     *
     * Get All
     *
     * @param  \DateTime $from_date (required)
     * @param  int $vertical_id (optional)
     * @param  int $offer_id (optional)
     * @param  int $affiliate_id (optional)
     * @param  int $campaign_id (optional)
     * @param  int $advertiser_id (optional)
     * @param  string $status (optional)
     * @param  string $show_goal (optional)
     * @param  string $show_non_goal (optional)
     * @param  string $show_throttled (optional)
     * @param  string $show_non_throttled (optional)
     * @param  string $show_test (optional)
     * @param  string $show_non_test (optional)
     * @param  \DateTime $to_date (optional)
     * @param  int $start (optional)
     * @param  int $limit (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function conversionsgetAlldoAsyncWithHttpInfo($from_date, $vertical_id = null, $offer_id = null, $affiliate_id = null, $campaign_id = null, $advertiser_id = null, $status = null, $show_goal = null, $show_non_goal = null, $show_throttled = null, $show_non_throttled = null, $show_test = null, $show_non_test = null, $to_date = null, $start = null, $limit = null)
    {
        $returnType = '';
        $request = $this->conversionsgetAlldoRequest($from_date, $vertical_id, $offer_id, $affiliate_id, $campaign_id, $advertiser_id, $status, $show_goal, $show_non_goal, $show_throttled, $show_non_throttled, $show_test, $show_non_test, $to_date, $start, $limit);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'conversionsgetAlldo'
     *
     * @param  \DateTime $from_date (required)
     * @param  int $vertical_id (optional)
     * @param  int $offer_id (optional)
     * @param  int $affiliate_id (optional)
     * @param  int $campaign_id (optional)
     * @param  int $advertiser_id (optional)
     * @param  string $status (optional)
     * @param  string $show_goal (optional)
     * @param  string $show_non_goal (optional)
     * @param  string $show_throttled (optional)
     * @param  string $show_non_throttled (optional)
     * @param  string $show_test (optional)
     * @param  string $show_non_test (optional)
     * @param  \DateTime $to_date (optional)
     * @param  int $start (optional)
     * @param  int $limit (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function conversionsgetAlldoRequest($from_date, $vertical_id = null, $offer_id = null, $affiliate_id = null, $campaign_id = null, $advertiser_id = null, $status = null, $show_goal = null, $show_non_goal = null, $show_throttled = null, $show_non_throttled = null, $show_test = null, $show_non_test = null, $to_date = null, $start = null, $limit = null)
    {
        // verify the required parameter 'from_date' is set
        if ($from_date === null || (is_array($from_date) && count($from_date) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $from_date when calling conversionsgetAlldo'
            );
        }

        $resourcePath = '/conversions/getAll.do';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($vertical_id !== null) {
            $queryParams['verticalID'] = ObjectSerializer::toQueryValue($vertical_id);
        }
        // query params
        if ($offer_id !== null) {
            $queryParams['offerID'] = ObjectSerializer::toQueryValue($offer_id);
        }
        // query params
        if ($affiliate_id !== null) {
            $queryParams['affiliateID'] = ObjectSerializer::toQueryValue($affiliate_id);
        }
        // query params
        if ($campaign_id !== null) {
            $queryParams['campaignID'] = ObjectSerializer::toQueryValue($campaign_id);
        }
        // query params
        if ($advertiser_id !== null) {
            $queryParams['advertiserID'] = ObjectSerializer::toQueryValue($advertiser_id);
        }
        // query params
        if ($status !== null) {
            $queryParams['status'] = ObjectSerializer::toQueryValue($status);
        }
        // query params
        if ($show_goal !== null) {
            $queryParams['showGoal'] = ObjectSerializer::toQueryValue($show_goal);
        }
        // query params
        if ($show_non_goal !== null) {
            $queryParams['showNonGoal'] = ObjectSerializer::toQueryValue($show_non_goal);
        }
        // query params
        if ($show_throttled !== null) {
            $queryParams['showThrottled'] = ObjectSerializer::toQueryValue($show_throttled);
        }
        // query params
        if ($show_non_throttled !== null) {
            $queryParams['showNonThrottled'] = ObjectSerializer::toQueryValue($show_non_throttled);
        }
        // query params
        if ($show_test !== null) {
            $queryParams['showTest'] = ObjectSerializer::toQueryValue($show_test);
        }
        // query params
        if ($show_non_test !== null) {
            $queryParams['showNonTest'] = ObjectSerializer::toQueryValue($show_non_test);
        }
        // query params
        if ($from_date !== null) {
            $queryParams['fromDate'] = ObjectSerializer::toQueryValue($from_date);
        }
        // query params
        if ($to_date !== null) {
            $queryParams['toDate'] = ObjectSerializer::toQueryValue($to_date);
        }
        // query params
        if ($start !== null) {
            $queryParams['start'] = ObjectSerializer::toQueryValue($start);
        }
        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api_key');
        if ($apiKey !== null) {
            $queryParams['api_key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api_secret');
        if ($apiKey !== null) {
            $queryParams['api_secret'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
