<?php
/**
 * GoalsreportsApi
 * PHP version 5
 *
 * @category Class
 * @package  LeadspediaApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * LeadsPedia API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.10
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace LeadspediaApi\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use LeadspediaApi\ApiException;
use LeadspediaApi\Configuration;
use LeadspediaApi\HeaderSelector;
use LeadspediaApi\ObjectSerializer;

/**
 * GoalsreportsApi Class Doc Comment
 *
 * @category Class
 * @package  LeadspediaApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GoalsreportsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation goalsReportsgetGoalsByCampaignsReportdo
     *
     * Get Goals By Campaigns Report
     *
     * @param  \DateTime $from_date from_date (required)
     * @param  int $vertical_id vertical_id (optional)
     * @param  int $vertical_group_id vertical_group_id (optional)
     * @param  int $offer_id offer_id (optional)
     * @param  string $payout_model payout_model (optional)
     * @param  int $affiliate_id affiliate_id (optional)
     * @param  int $affiliate_account_manager_id affiliate_account_manager_id (optional)
     * @param  int $advertiser_id advertiser_id (optional)
     * @param  int $advertiser_account_manager_id advertiser_account_manager_id (optional)
     * @param  \DateTime $to_date to_date (optional)
     *
     * @throws \LeadspediaApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function goalsReportsgetGoalsByCampaignsReportdo($from_date, $vertical_id = null, $vertical_group_id = null, $offer_id = null, $payout_model = null, $affiliate_id = null, $affiliate_account_manager_id = null, $advertiser_id = null, $advertiser_account_manager_id = null, $to_date = null)
    {
        $this->goalsReportsgetGoalsByCampaignsReportdoWithHttpInfo($from_date, $vertical_id, $vertical_group_id, $offer_id, $payout_model, $affiliate_id, $affiliate_account_manager_id, $advertiser_id, $advertiser_account_manager_id, $to_date);
    }

    /**
     * Operation goalsReportsgetGoalsByCampaignsReportdoWithHttpInfo
     *
     * Get Goals By Campaigns Report
     *
     * @param  \DateTime $from_date (required)
     * @param  int $vertical_id (optional)
     * @param  int $vertical_group_id (optional)
     * @param  int $offer_id (optional)
     * @param  string $payout_model (optional)
     * @param  int $affiliate_id (optional)
     * @param  int $affiliate_account_manager_id (optional)
     * @param  int $advertiser_id (optional)
     * @param  int $advertiser_account_manager_id (optional)
     * @param  \DateTime $to_date (optional)
     *
     * @throws \LeadspediaApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function goalsReportsgetGoalsByCampaignsReportdoWithHttpInfo($from_date, $vertical_id = null, $vertical_group_id = null, $offer_id = null, $payout_model = null, $affiliate_id = null, $affiliate_account_manager_id = null, $advertiser_id = null, $advertiser_account_manager_id = null, $to_date = null)
    {
        $returnType = '';
        $request = $this->goalsReportsgetGoalsByCampaignsReportdoRequest($from_date, $vertical_id, $vertical_group_id, $offer_id, $payout_model, $affiliate_id, $affiliate_account_manager_id, $advertiser_id, $advertiser_account_manager_id, $to_date);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation goalsReportsgetGoalsByCampaignsReportdoAsync
     *
     * Get Goals By Campaigns Report
     *
     * @param  \DateTime $from_date (required)
     * @param  int $vertical_id (optional)
     * @param  int $vertical_group_id (optional)
     * @param  int $offer_id (optional)
     * @param  string $payout_model (optional)
     * @param  int $affiliate_id (optional)
     * @param  int $affiliate_account_manager_id (optional)
     * @param  int $advertiser_id (optional)
     * @param  int $advertiser_account_manager_id (optional)
     * @param  \DateTime $to_date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function goalsReportsgetGoalsByCampaignsReportdoAsync($from_date, $vertical_id = null, $vertical_group_id = null, $offer_id = null, $payout_model = null, $affiliate_id = null, $affiliate_account_manager_id = null, $advertiser_id = null, $advertiser_account_manager_id = null, $to_date = null)
    {
        return $this->goalsReportsgetGoalsByCampaignsReportdoAsyncWithHttpInfo($from_date, $vertical_id, $vertical_group_id, $offer_id, $payout_model, $affiliate_id, $affiliate_account_manager_id, $advertiser_id, $advertiser_account_manager_id, $to_date)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation goalsReportsgetGoalsByCampaignsReportdoAsyncWithHttpInfo
     *
     * Get Goals By Campaigns Report
     *
     * @param  \DateTime $from_date (required)
     * @param  int $vertical_id (optional)
     * @param  int $vertical_group_id (optional)
     * @param  int $offer_id (optional)
     * @param  string $payout_model (optional)
     * @param  int $affiliate_id (optional)
     * @param  int $affiliate_account_manager_id (optional)
     * @param  int $advertiser_id (optional)
     * @param  int $advertiser_account_manager_id (optional)
     * @param  \DateTime $to_date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function goalsReportsgetGoalsByCampaignsReportdoAsyncWithHttpInfo($from_date, $vertical_id = null, $vertical_group_id = null, $offer_id = null, $payout_model = null, $affiliate_id = null, $affiliate_account_manager_id = null, $advertiser_id = null, $advertiser_account_manager_id = null, $to_date = null)
    {
        $returnType = '';
        $request = $this->goalsReportsgetGoalsByCampaignsReportdoRequest($from_date, $vertical_id, $vertical_group_id, $offer_id, $payout_model, $affiliate_id, $affiliate_account_manager_id, $advertiser_id, $advertiser_account_manager_id, $to_date);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'goalsReportsgetGoalsByCampaignsReportdo'
     *
     * @param  \DateTime $from_date (required)
     * @param  int $vertical_id (optional)
     * @param  int $vertical_group_id (optional)
     * @param  int $offer_id (optional)
     * @param  string $payout_model (optional)
     * @param  int $affiliate_id (optional)
     * @param  int $affiliate_account_manager_id (optional)
     * @param  int $advertiser_id (optional)
     * @param  int $advertiser_account_manager_id (optional)
     * @param  \DateTime $to_date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function goalsReportsgetGoalsByCampaignsReportdoRequest($from_date, $vertical_id = null, $vertical_group_id = null, $offer_id = null, $payout_model = null, $affiliate_id = null, $affiliate_account_manager_id = null, $advertiser_id = null, $advertiser_account_manager_id = null, $to_date = null)
    {
        // verify the required parameter 'from_date' is set
        if ($from_date === null || (is_array($from_date) && count($from_date) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $from_date when calling goalsReportsgetGoalsByCampaignsReportdo'
            );
        }

        $resourcePath = '/goalsReports/getGoalsByCampaignsReport.do';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($vertical_id !== null) {
            $queryParams['verticalID'] = ObjectSerializer::toQueryValue($vertical_id);
        }
        // query params
        if ($vertical_group_id !== null) {
            $queryParams['verticalGroupID'] = ObjectSerializer::toQueryValue($vertical_group_id);
        }
        // query params
        if ($offer_id !== null) {
            $queryParams['offerID'] = ObjectSerializer::toQueryValue($offer_id);
        }
        // query params
        if ($payout_model !== null) {
            $queryParams['payoutModel'] = ObjectSerializer::toQueryValue($payout_model);
        }
        // query params
        if ($affiliate_id !== null) {
            $queryParams['affiliateID'] = ObjectSerializer::toQueryValue($affiliate_id);
        }
        // query params
        if ($affiliate_account_manager_id !== null) {
            $queryParams['affiliateAccountManagerID'] = ObjectSerializer::toQueryValue($affiliate_account_manager_id);
        }
        // query params
        if ($advertiser_id !== null) {
            $queryParams['advertiserID'] = ObjectSerializer::toQueryValue($advertiser_id);
        }
        // query params
        if ($advertiser_account_manager_id !== null) {
            $queryParams['advertiserAccountManagerID'] = ObjectSerializer::toQueryValue($advertiser_account_manager_id);
        }
        // query params
        if ($from_date !== null) {
            $queryParams['fromDate'] = ObjectSerializer::toQueryValue($from_date);
        }
        // query params
        if ($to_date !== null) {
            $queryParams['toDate'] = ObjectSerializer::toQueryValue($to_date);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api_key');
        if ($apiKey !== null) {
            $queryParams['api_key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api_secret');
        if ($apiKey !== null) {
            $queryParams['api_secret'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation goalsReportsgetGoalsBySourceReportdo
     *
     * Get Goals By Source Report
     *
     * @param  \DateTime $from_date from_date (required)
     * @param  int $offer_id offer_id (optional)
     * @param  int $affiliate_id affiliate_id (optional)
     * @param  int $affiliate_account_manager_id affiliate_account_manager_id (optional)
     * @param  \DateTime $to_date to_date (optional)
     *
     * @throws \LeadspediaApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function goalsReportsgetGoalsBySourceReportdo($from_date, $offer_id = null, $affiliate_id = null, $affiliate_account_manager_id = null, $to_date = null)
    {
        $this->goalsReportsgetGoalsBySourceReportdoWithHttpInfo($from_date, $offer_id, $affiliate_id, $affiliate_account_manager_id, $to_date);
    }

    /**
     * Operation goalsReportsgetGoalsBySourceReportdoWithHttpInfo
     *
     * Get Goals By Source Report
     *
     * @param  \DateTime $from_date (required)
     * @param  int $offer_id (optional)
     * @param  int $affiliate_id (optional)
     * @param  int $affiliate_account_manager_id (optional)
     * @param  \DateTime $to_date (optional)
     *
     * @throws \LeadspediaApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function goalsReportsgetGoalsBySourceReportdoWithHttpInfo($from_date, $offer_id = null, $affiliate_id = null, $affiliate_account_manager_id = null, $to_date = null)
    {
        $returnType = '';
        $request = $this->goalsReportsgetGoalsBySourceReportdoRequest($from_date, $offer_id, $affiliate_id, $affiliate_account_manager_id, $to_date);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation goalsReportsgetGoalsBySourceReportdoAsync
     *
     * Get Goals By Source Report
     *
     * @param  \DateTime $from_date (required)
     * @param  int $offer_id (optional)
     * @param  int $affiliate_id (optional)
     * @param  int $affiliate_account_manager_id (optional)
     * @param  \DateTime $to_date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function goalsReportsgetGoalsBySourceReportdoAsync($from_date, $offer_id = null, $affiliate_id = null, $affiliate_account_manager_id = null, $to_date = null)
    {
        return $this->goalsReportsgetGoalsBySourceReportdoAsyncWithHttpInfo($from_date, $offer_id, $affiliate_id, $affiliate_account_manager_id, $to_date)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation goalsReportsgetGoalsBySourceReportdoAsyncWithHttpInfo
     *
     * Get Goals By Source Report
     *
     * @param  \DateTime $from_date (required)
     * @param  int $offer_id (optional)
     * @param  int $affiliate_id (optional)
     * @param  int $affiliate_account_manager_id (optional)
     * @param  \DateTime $to_date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function goalsReportsgetGoalsBySourceReportdoAsyncWithHttpInfo($from_date, $offer_id = null, $affiliate_id = null, $affiliate_account_manager_id = null, $to_date = null)
    {
        $returnType = '';
        $request = $this->goalsReportsgetGoalsBySourceReportdoRequest($from_date, $offer_id, $affiliate_id, $affiliate_account_manager_id, $to_date);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'goalsReportsgetGoalsBySourceReportdo'
     *
     * @param  \DateTime $from_date (required)
     * @param  int $offer_id (optional)
     * @param  int $affiliate_id (optional)
     * @param  int $affiliate_account_manager_id (optional)
     * @param  \DateTime $to_date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function goalsReportsgetGoalsBySourceReportdoRequest($from_date, $offer_id = null, $affiliate_id = null, $affiliate_account_manager_id = null, $to_date = null)
    {
        // verify the required parameter 'from_date' is set
        if ($from_date === null || (is_array($from_date) && count($from_date) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $from_date when calling goalsReportsgetGoalsBySourceReportdo'
            );
        }

        $resourcePath = '/goalsReports/getGoalsBySourceReport.do';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($offer_id !== null) {
            $queryParams['offerID'] = ObjectSerializer::toQueryValue($offer_id);
        }
        // query params
        if ($affiliate_id !== null) {
            $queryParams['affiliateID'] = ObjectSerializer::toQueryValue($affiliate_id);
        }
        // query params
        if ($affiliate_account_manager_id !== null) {
            $queryParams['affiliateAccountManagerID'] = ObjectSerializer::toQueryValue($affiliate_account_manager_id);
        }
        // query params
        if ($from_date !== null) {
            $queryParams['fromDate'] = ObjectSerializer::toQueryValue($from_date);
        }
        // query params
        if ($to_date !== null) {
            $queryParams['toDate'] = ObjectSerializer::toQueryValue($to_date);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api_key');
        if ($apiKey !== null) {
            $queryParams['api_key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api_secret');
        if ($apiKey !== null) {
            $queryParams['api_secret'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation goalsReportsgetGoalsBySubAffiliatesReportdo
     *
     * Get Goals By Sub Affiliates Report
     *
     * @param  \DateTime $from_date from_date (required)
     * @param  int $offer_id offer_id (optional)
     * @param  int $affiliate_id affiliate_id (optional)
     * @param  int $affiliate_account_manager_id affiliate_account_manager_id (optional)
     * @param  \DateTime $to_date to_date (optional)
     *
     * @throws \LeadspediaApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function goalsReportsgetGoalsBySubAffiliatesReportdo($from_date, $offer_id = null, $affiliate_id = null, $affiliate_account_manager_id = null, $to_date = null)
    {
        $this->goalsReportsgetGoalsBySubAffiliatesReportdoWithHttpInfo($from_date, $offer_id, $affiliate_id, $affiliate_account_manager_id, $to_date);
    }

    /**
     * Operation goalsReportsgetGoalsBySubAffiliatesReportdoWithHttpInfo
     *
     * Get Goals By Sub Affiliates Report
     *
     * @param  \DateTime $from_date (required)
     * @param  int $offer_id (optional)
     * @param  int $affiliate_id (optional)
     * @param  int $affiliate_account_manager_id (optional)
     * @param  \DateTime $to_date (optional)
     *
     * @throws \LeadspediaApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function goalsReportsgetGoalsBySubAffiliatesReportdoWithHttpInfo($from_date, $offer_id = null, $affiliate_id = null, $affiliate_account_manager_id = null, $to_date = null)
    {
        $returnType = '';
        $request = $this->goalsReportsgetGoalsBySubAffiliatesReportdoRequest($from_date, $offer_id, $affiliate_id, $affiliate_account_manager_id, $to_date);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation goalsReportsgetGoalsBySubAffiliatesReportdoAsync
     *
     * Get Goals By Sub Affiliates Report
     *
     * @param  \DateTime $from_date (required)
     * @param  int $offer_id (optional)
     * @param  int $affiliate_id (optional)
     * @param  int $affiliate_account_manager_id (optional)
     * @param  \DateTime $to_date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function goalsReportsgetGoalsBySubAffiliatesReportdoAsync($from_date, $offer_id = null, $affiliate_id = null, $affiliate_account_manager_id = null, $to_date = null)
    {
        return $this->goalsReportsgetGoalsBySubAffiliatesReportdoAsyncWithHttpInfo($from_date, $offer_id, $affiliate_id, $affiliate_account_manager_id, $to_date)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation goalsReportsgetGoalsBySubAffiliatesReportdoAsyncWithHttpInfo
     *
     * Get Goals By Sub Affiliates Report
     *
     * @param  \DateTime $from_date (required)
     * @param  int $offer_id (optional)
     * @param  int $affiliate_id (optional)
     * @param  int $affiliate_account_manager_id (optional)
     * @param  \DateTime $to_date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function goalsReportsgetGoalsBySubAffiliatesReportdoAsyncWithHttpInfo($from_date, $offer_id = null, $affiliate_id = null, $affiliate_account_manager_id = null, $to_date = null)
    {
        $returnType = '';
        $request = $this->goalsReportsgetGoalsBySubAffiliatesReportdoRequest($from_date, $offer_id, $affiliate_id, $affiliate_account_manager_id, $to_date);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'goalsReportsgetGoalsBySubAffiliatesReportdo'
     *
     * @param  \DateTime $from_date (required)
     * @param  int $offer_id (optional)
     * @param  int $affiliate_id (optional)
     * @param  int $affiliate_account_manager_id (optional)
     * @param  \DateTime $to_date (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function goalsReportsgetGoalsBySubAffiliatesReportdoRequest($from_date, $offer_id = null, $affiliate_id = null, $affiliate_account_manager_id = null, $to_date = null)
    {
        // verify the required parameter 'from_date' is set
        if ($from_date === null || (is_array($from_date) && count($from_date) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $from_date when calling goalsReportsgetGoalsBySubAffiliatesReportdo'
            );
        }

        $resourcePath = '/goalsReports/getGoalsBySubAffiliatesReport.do';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($offer_id !== null) {
            $queryParams['offerID'] = ObjectSerializer::toQueryValue($offer_id);
        }
        // query params
        if ($affiliate_id !== null) {
            $queryParams['affiliateID'] = ObjectSerializer::toQueryValue($affiliate_id);
        }
        // query params
        if ($affiliate_account_manager_id !== null) {
            $queryParams['affiliateAccountManagerID'] = ObjectSerializer::toQueryValue($affiliate_account_manager_id);
        }
        // query params
        if ($from_date !== null) {
            $queryParams['fromDate'] = ObjectSerializer::toQueryValue($from_date);
        }
        // query params
        if ($to_date !== null) {
            $queryParams['toDate'] = ObjectSerializer::toQueryValue($to_date);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api_key');
        if ($apiKey !== null) {
            $queryParams['api_key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api_secret');
        if ($apiKey !== null) {
            $queryParams['api_secret'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
