<?php
/**
 * AffiliatesContactsApi
 * PHP version 5
 *
 * @category Class
 * @package  Leadspedia
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LeadsPedia API Reference
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Leadspedia\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Leadspedia\ApiException;
use Leadspedia\Configuration;
use Leadspedia\HeaderSelector;
use Leadspedia\ObjectSerializer;

/**
 * AffiliatesContactsApi Class Doc Comment
 *
 * @category Class
 * @package  Leadspedia
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AffiliatesContactsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $host_index (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $host_index = 0
    ) {
        $this->client         = $client ?: new Client();
        $this->config         = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex      = $host_index;
    }

    /**
     * Set the host index
     *
     * @param  int Host index (required)
     */
    public function setHostIndex($host_index): void
    {
        $this->hostIndex = $host_index;
    }

    /**
     * Get the host index
     *
     * @return Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation affiliatesContactschangePassworddo
     *
     * Change Password
     *
     * @param  int $contactID contactID (required)
     * @param  string $oldPassword oldPassword (required)
     * @param  string $newPassword newPassword (required)
     *
     * @throws \Leadspedia\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function affiliatesContactschangePassworddo($contactID, $oldPassword, $newPassword): void
    {
        $this->affiliatesContactschangePassworddoWithHttpInfo($contactID, $oldPassword, $newPassword);
    }

    /**
     * Operation affiliatesContactschangePassworddoWithHttpInfo
     *
     * Change Password
     *
     * @param  int $contactID (required)
     * @param  string $oldPassword (required)
     * @param  string $newPassword (required)
     *
     * @throws \Leadspedia\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function affiliatesContactschangePassworddoWithHttpInfo($contactID, $oldPassword, $newPassword)
    {
        $request = $this->affiliatesContactschangePassworddoRequest($contactID, $oldPassword, $newPassword);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation affiliatesContactschangePassworddoAsync
     *
     * Change Password
     *
     * @param  int $contactID (required)
     * @param  string $oldPassword (required)
     * @param  string $newPassword (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function affiliatesContactschangePassworddoAsync($contactID, $oldPassword, $newPassword)
    {
        return $this->affiliatesContactschangePassworddoAsyncWithHttpInfo($contactID, $oldPassword, $newPassword)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation affiliatesContactschangePassworddoAsyncWithHttpInfo
     *
     * Change Password
     *
     * @param  int $contactID (required)
     * @param  string $oldPassword (required)
     * @param  string $newPassword (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function affiliatesContactschangePassworddoAsyncWithHttpInfo($contactID, $oldPassword, $newPassword)
    {
        $returnType = '';
        $request    = $this->affiliatesContactschangePassworddoRequest($contactID, $oldPassword, $newPassword);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception): void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'affiliatesContactschangePassworddo'
     *
     * @param  int $contactID (required)
     * @param  string $oldPassword (required)
     * @param  string $newPassword (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function affiliatesContactschangePassworddoRequest($contactID, $oldPassword, $newPassword)
    {
        // verify the required parameter 'contactID' is set
        if ($contactID === null || (is_array($contactID) && count($contactID) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $contactID when calling affiliatesContactschangePassworddo'
            );
        }
        // verify the required parameter 'oldPassword' is set
        if ($oldPassword === null || (is_array($oldPassword) && count($oldPassword) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $oldPassword when calling affiliatesContactschangePassworddo'
            );
        }
        // verify the required parameter 'newPassword' is set
        if ($newPassword === null || (is_array($newPassword) && count($newPassword) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $newPassword when calling affiliatesContactschangePassworddo'
            );
        }

        $resourcePath = '/affiliatesContacts/changePassword.do';
        $formParams   = [];
        $queryParams  = [];
        $headerParams = [];
        $httpBody     = '';
        $multipart    = false;

        // query params
        if ($contactID !== null) {
            $queryParams['contactID'] = ObjectSerializer::toQueryValue($contactID);
        }
        // query params
        if ($oldPassword !== null) {
            $queryParams['oldPassword'] = ObjectSerializer::toQueryValue($oldPassword);
        }
        // query params
        if ($newPassword !== null) {
            $queryParams['newPassword'] = ObjectSerializer::toQueryValue($newPassword);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name'     => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api_key');
        if ($apiKey !== null) {
            $queryParams['api_key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api_secret');
        if ($apiKey !== null) {
            $queryParams['api_secret'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation affiliatesContactschangeStatusdo
     *
     * Change Status
     *
     * @param  int $contactID contactID (required)
     * @param  string $status status (required)
     *
     * @throws \Leadspedia\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function affiliatesContactschangeStatusdo($contactID, $status): void
    {
        $this->affiliatesContactschangeStatusdoWithHttpInfo($contactID, $status);
    }

    /**
     * Operation affiliatesContactschangeStatusdoWithHttpInfo
     *
     * Change Status
     *
     * @param  int $contactID (required)
     * @param  string $status (required)
     *
     * @throws \Leadspedia\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function affiliatesContactschangeStatusdoWithHttpInfo($contactID, $status)
    {
        $request = $this->affiliatesContactschangeStatusdoRequest($contactID, $status);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation affiliatesContactschangeStatusdoAsync
     *
     * Change Status
     *
     * @param  int $contactID (required)
     * @param  string $status (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function affiliatesContactschangeStatusdoAsync($contactID, $status)
    {
        return $this->affiliatesContactschangeStatusdoAsyncWithHttpInfo($contactID, $status)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation affiliatesContactschangeStatusdoAsyncWithHttpInfo
     *
     * Change Status
     *
     * @param  int $contactID (required)
     * @param  string $status (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function affiliatesContactschangeStatusdoAsyncWithHttpInfo($contactID, $status)
    {
        $returnType = '';
        $request    = $this->affiliatesContactschangeStatusdoRequest($contactID, $status);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception): void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'affiliatesContactschangeStatusdo'
     *
     * @param  int $contactID (required)
     * @param  string $status (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function affiliatesContactschangeStatusdoRequest($contactID, $status)
    {
        // verify the required parameter 'contactID' is set
        if ($contactID === null || (is_array($contactID) && count($contactID) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $contactID when calling affiliatesContactschangeStatusdo'
            );
        }
        // verify the required parameter 'status' is set
        if ($status === null || (is_array($status) && count($status) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $status when calling affiliatesContactschangeStatusdo'
            );
        }

        $resourcePath = '/affiliatesContacts/changeStatus.do';
        $formParams   = [];
        $queryParams  = [];
        $headerParams = [];
        $httpBody     = '';
        $multipart    = false;

        // query params
        if ($contactID !== null) {
            $queryParams['contactID'] = ObjectSerializer::toQueryValue($contactID);
        }
        // query params
        if ($status !== null) {
            $queryParams['status'] = ObjectSerializer::toQueryValue($status);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name'     => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api_key');
        if ($apiKey !== null) {
            $queryParams['api_key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api_secret');
        if ($apiKey !== null) {
            $queryParams['api_secret'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation affiliatesContactscreatedo
     *
     * Create
     *
     * @param  int $affiliateID affiliateID (required)
     * @param  string $firstName firstName (required)
     * @param  string $lastName lastName (required)
     * @param  string $emailAddress emailAddress (required)
     * @param  string $password password (required)
     * @param  string $jobTitle jobTitle (optional)
     * @param  string $phoneNumber phoneNumber (optional)
     * @param  string $portalAccess portalAccess (optional, default to 'No')
     * @param  string $status status (optional, default to 'Active')
     *
     * @throws \Leadspedia\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function affiliatesContactscreatedo($affiliateID, $firstName, $lastName, $emailAddress, $password, $jobTitle = null, $phoneNumber = null, $portalAccess = 'No', $status = 'Active'): void
    {
        $this->affiliatesContactscreatedoWithHttpInfo($affiliateID, $firstName, $lastName, $emailAddress, $password, $jobTitle, $phoneNumber, $portalAccess, $status);
    }

    /**
     * Operation affiliatesContactscreatedoWithHttpInfo
     *
     * Create
     *
     * @param  int $affiliateID (required)
     * @param  string $firstName (required)
     * @param  string $lastName (required)
     * @param  string $emailAddress (required)
     * @param  string $password (required)
     * @param  string $jobTitle (optional)
     * @param  string $phoneNumber (optional)
     * @param  string $portalAccess (optional, default to 'No')
     * @param  string $status (optional, default to 'Active')
     *
     * @throws \Leadspedia\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function affiliatesContactscreatedoWithHttpInfo($affiliateID, $firstName, $lastName, $emailAddress, $password, $jobTitle = null, $phoneNumber = null, $portalAccess = 'No', $status = 'Active')
    {
        $request = $this->affiliatesContactscreatedoRequest($affiliateID, $firstName, $lastName, $emailAddress, $password, $jobTitle, $phoneNumber, $portalAccess, $status);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation affiliatesContactscreatedoAsync
     *
     * Create
     *
     * @param  int $affiliateID (required)
     * @param  string $firstName (required)
     * @param  string $lastName (required)
     * @param  string $emailAddress (required)
     * @param  string $password (required)
     * @param  string $jobTitle (optional)
     * @param  string $phoneNumber (optional)
     * @param  string $portalAccess (optional, default to 'No')
     * @param  string $status (optional, default to 'Active')
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function affiliatesContactscreatedoAsync($affiliateID, $firstName, $lastName, $emailAddress, $password, $jobTitle = null, $phoneNumber = null, $portalAccess = 'No', $status = 'Active')
    {
        return $this->affiliatesContactscreatedoAsyncWithHttpInfo($affiliateID, $firstName, $lastName, $emailAddress, $password, $jobTitle, $phoneNumber, $portalAccess, $status)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation affiliatesContactscreatedoAsyncWithHttpInfo
     *
     * Create
     *
     * @param  int $affiliateID (required)
     * @param  string $firstName (required)
     * @param  string $lastName (required)
     * @param  string $emailAddress (required)
     * @param  string $password (required)
     * @param  string $jobTitle (optional)
     * @param  string $phoneNumber (optional)
     * @param  string $portalAccess (optional, default to 'No')
     * @param  string $status (optional, default to 'Active')
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function affiliatesContactscreatedoAsyncWithHttpInfo($affiliateID, $firstName, $lastName, $emailAddress, $password, $jobTitle = null, $phoneNumber = null, $portalAccess = 'No', $status = 'Active')
    {
        $returnType = '';
        $request    = $this->affiliatesContactscreatedoRequest($affiliateID, $firstName, $lastName, $emailAddress, $password, $jobTitle, $phoneNumber, $portalAccess, $status);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception): void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'affiliatesContactscreatedo'
     *
     * @param  int $affiliateID (required)
     * @param  string $firstName (required)
     * @param  string $lastName (required)
     * @param  string $emailAddress (required)
     * @param  string $password (required)
     * @param  string $jobTitle (optional)
     * @param  string $phoneNumber (optional)
     * @param  string $portalAccess (optional, default to 'No')
     * @param  string $status (optional, default to 'Active')
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function affiliatesContactscreatedoRequest($affiliateID, $firstName, $lastName, $emailAddress, $password, $jobTitle = null, $phoneNumber = null, $portalAccess = 'No', $status = 'Active')
    {
        // verify the required parameter 'affiliateID' is set
        if ($affiliateID === null || (is_array($affiliateID) && count($affiliateID) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $affiliateID when calling affiliatesContactscreatedo'
            );
        }
        // verify the required parameter 'firstName' is set
        if ($firstName === null || (is_array($firstName) && count($firstName) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $firstName when calling affiliatesContactscreatedo'
            );
        }
        // verify the required parameter 'lastName' is set
        if ($lastName === null || (is_array($lastName) && count($lastName) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $lastName when calling affiliatesContactscreatedo'
            );
        }
        // verify the required parameter 'emailAddress' is set
        if ($emailAddress === null || (is_array($emailAddress) && count($emailAddress) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $emailAddress when calling affiliatesContactscreatedo'
            );
        }
        // verify the required parameter 'password' is set
        if ($password === null || (is_array($password) && count($password) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $password when calling affiliatesContactscreatedo'
            );
        }

        $resourcePath = '/affiliatesContacts/create.do';
        $formParams   = [];
        $queryParams  = [];
        $headerParams = [];
        $httpBody     = '';
        $multipart    = false;

        // query params
        if ($affiliateID !== null) {
            $queryParams['affiliateID'] = ObjectSerializer::toQueryValue($affiliateID);
        }
        // query params
        if ($firstName !== null) {
            $queryParams['firstName'] = ObjectSerializer::toQueryValue($firstName);
        }
        // query params
        if ($lastName !== null) {
            $queryParams['lastName'] = ObjectSerializer::toQueryValue($lastName);
        }
        // query params
        if ($emailAddress !== null) {
            $queryParams['emailAddress'] = ObjectSerializer::toQueryValue($emailAddress);
        }
        // query params
        if ($password !== null) {
            $queryParams['password'] = ObjectSerializer::toQueryValue($password);
        }
        // query params
        if ($jobTitle !== null) {
            $queryParams['jobTitle'] = ObjectSerializer::toQueryValue($jobTitle);
        }
        // query params
        if ($phoneNumber !== null) {
            $queryParams['phoneNumber'] = ObjectSerializer::toQueryValue($phoneNumber);
        }
        // query params
        if ($portalAccess !== null) {
            $queryParams['portalAccess'] = ObjectSerializer::toQueryValue($portalAccess);
        }
        // query params
        if ($status !== null) {
            $queryParams['status'] = ObjectSerializer::toQueryValue($status);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name'     => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api_key');
        if ($apiKey !== null) {
            $queryParams['api_key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api_secret');
        if ($apiKey !== null) {
            $queryParams['api_secret'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation affiliatesContactsdeletedo
     *
     * Delete
     *
     * @param  int $contactID contactID (required)
     *
     * @throws \Leadspedia\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function affiliatesContactsdeletedo($contactID): void
    {
        $this->affiliatesContactsdeletedoWithHttpInfo($contactID);
    }

    /**
     * Operation affiliatesContactsdeletedoWithHttpInfo
     *
     * Delete
     *
     * @param  int $contactID (required)
     *
     * @throws \Leadspedia\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function affiliatesContactsdeletedoWithHttpInfo($contactID)
    {
        $request = $this->affiliatesContactsdeletedoRequest($contactID);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation affiliatesContactsdeletedoAsync
     *
     * Delete
     *
     * @param  int $contactID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function affiliatesContactsdeletedoAsync($contactID)
    {
        return $this->affiliatesContactsdeletedoAsyncWithHttpInfo($contactID)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation affiliatesContactsdeletedoAsyncWithHttpInfo
     *
     * Delete
     *
     * @param  int $contactID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function affiliatesContactsdeletedoAsyncWithHttpInfo($contactID)
    {
        $returnType = '';
        $request    = $this->affiliatesContactsdeletedoRequest($contactID);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception): void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'affiliatesContactsdeletedo'
     *
     * @param  int $contactID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function affiliatesContactsdeletedoRequest($contactID)
    {
        // verify the required parameter 'contactID' is set
        if ($contactID === null || (is_array($contactID) && count($contactID) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $contactID when calling affiliatesContactsdeletedo'
            );
        }

        $resourcePath = '/affiliatesContacts/delete.do';
        $formParams   = [];
        $queryParams  = [];
        $headerParams = [];
        $httpBody     = '';
        $multipart    = false;

        // query params
        if ($contactID !== null) {
            $queryParams['contactID'] = ObjectSerializer::toQueryValue($contactID);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name'     => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api_key');
        if ($apiKey !== null) {
            $queryParams['api_key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api_secret');
        if ($apiKey !== null) {
            $queryParams['api_secret'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation affiliatesContactsgetAlldo
     *
     * Get All
     *
     * @param  int $contactID contactID (optional)
     * @param  int $affiliateID affiliateID (optional)
     * @param  string $portalAccess portalAccess (optional)
     * @param  int $start start (optional, default to 0)
     * @param  int $limit limit (optional, default to 100)
     *
     * @throws \Leadspedia\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object
     */
    public function affiliatesContactsgetAlldo($contactID = null, $affiliateID = null, $portalAccess = null, $start = 0, $limit = 100)
    {
        list($response) = $this->affiliatesContactsgetAlldoWithHttpInfo($contactID, $affiliateID, $portalAccess, $start, $limit);
        return $response;
    }

    /**
     * Operation affiliatesContactsgetAlldoWithHttpInfo
     *
     * Get All
     *
     * @param  int $contactID (optional)
     * @param  int $affiliateID (optional)
     * @param  string $portalAccess (optional)
     * @param  int $start (optional, default to 0)
     * @param  int $limit (optional, default to 100)
     *
     * @throws \Leadspedia\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of object, HTTP status code, HTTP response headers (array of strings)
     */
    public function affiliatesContactsgetAlldoWithHttpInfo($contactID = null, $affiliateID = null, $portalAccess = null, $start = 0, $limit = 100)
    {
        $request = $this->affiliatesContactsgetAlldoRequest($contactID, $affiliateID, $portalAccess, $start, $limit);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch ($statusCode) {
                case 200:
                    if ('object' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'object', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType   = 'object';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation affiliatesContactsgetAlldoAsync
     *
     * Get All
     *
     * @param  int $contactID (optional)
     * @param  int $affiliateID (optional)
     * @param  string $portalAccess (optional)
     * @param  int $start (optional, default to 0)
     * @param  int $limit (optional, default to 100)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function affiliatesContactsgetAlldoAsync($contactID = null, $affiliateID = null, $portalAccess = null, $start = 0, $limit = 100)
    {
        return $this->affiliatesContactsgetAlldoAsyncWithHttpInfo($contactID, $affiliateID, $portalAccess, $start, $limit)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation affiliatesContactsgetAlldoAsyncWithHttpInfo
     *
     * Get All
     *
     * @param  int $contactID (optional)
     * @param  int $affiliateID (optional)
     * @param  string $portalAccess (optional)
     * @param  int $start (optional, default to 0)
     * @param  int $limit (optional, default to 100)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function affiliatesContactsgetAlldoAsyncWithHttpInfo($contactID = null, $affiliateID = null, $portalAccess = null, $start = 0, $limit = 100)
    {
        $returnType = 'object';
        $request    = $this->affiliatesContactsgetAlldoRequest($contactID, $affiliateID, $portalAccess, $start, $limit);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception): void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'affiliatesContactsgetAlldo'
     *
     * @param  int $contactID (optional)
     * @param  int $affiliateID (optional)
     * @param  string $portalAccess (optional)
     * @param  int $start (optional, default to 0)
     * @param  int $limit (optional, default to 100)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function affiliatesContactsgetAlldoRequest($contactID = null, $affiliateID = null, $portalAccess = null, $start = 0, $limit = 100)
    {
        $resourcePath = '/affiliatesContacts/getAll.do';
        $formParams   = [];
        $queryParams  = [];
        $headerParams = [];
        $httpBody     = '';
        $multipart    = false;

        // query params
        if ($contactID !== null) {
            $queryParams['contactID'] = ObjectSerializer::toQueryValue($contactID);
        }
        // query params
        if ($affiliateID !== null) {
            $queryParams['affiliateID'] = ObjectSerializer::toQueryValue($affiliateID);
        }
        // query params
        if ($portalAccess !== null) {
            $queryParams['portalAccess'] = ObjectSerializer::toQueryValue($portalAccess);
        }
        // query params
        if ($start !== null) {
            $queryParams['start'] = ObjectSerializer::toQueryValue($start);
        }
        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name'     => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api_key');
        if ($apiKey !== null) {
            $queryParams['api_key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api_secret');
        if ($apiKey !== null) {
            $queryParams['api_secret'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation affiliatesContactsgetInfodo
     *
     * Get Info
     *
     * @param  int $contactID contactID (required)
     *
     * @throws \Leadspedia\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object
     */
    public function affiliatesContactsgetInfodo($contactID)
    {
        list($response) = $this->affiliatesContactsgetInfodoWithHttpInfo($contactID);
        return $response;
    }

    /**
     * Operation affiliatesContactsgetInfodoWithHttpInfo
     *
     * Get Info
     *
     * @param  int $contactID (required)
     *
     * @throws \Leadspedia\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of object, HTTP status code, HTTP response headers (array of strings)
     */
    public function affiliatesContactsgetInfodoWithHttpInfo($contactID)
    {
        $request = $this->affiliatesContactsgetInfodoRequest($contactID);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch ($statusCode) {
                case 200:
                    if ('object' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'object', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType   = 'object';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation affiliatesContactsgetInfodoAsync
     *
     * Get Info
     *
     * @param  int $contactID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function affiliatesContactsgetInfodoAsync($contactID)
    {
        return $this->affiliatesContactsgetInfodoAsyncWithHttpInfo($contactID)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation affiliatesContactsgetInfodoAsyncWithHttpInfo
     *
     * Get Info
     *
     * @param  int $contactID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function affiliatesContactsgetInfodoAsyncWithHttpInfo($contactID)
    {
        $returnType = 'object';
        $request    = $this->affiliatesContactsgetInfodoRequest($contactID);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception): void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'affiliatesContactsgetInfodo'
     *
     * @param  int $contactID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function affiliatesContactsgetInfodoRequest($contactID)
    {
        // verify the required parameter 'contactID' is set
        if ($contactID === null || (is_array($contactID) && count($contactID) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $contactID when calling affiliatesContactsgetInfodo'
            );
        }

        $resourcePath = '/affiliatesContacts/getInfo.do';
        $formParams   = [];
        $queryParams  = [];
        $headerParams = [];
        $httpBody     = '';
        $multipart    = false;

        // query params
        if ($contactID !== null) {
            $queryParams['contactID'] = ObjectSerializer::toQueryValue($contactID);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name'     => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api_key');
        if ($apiKey !== null) {
            $queryParams['api_key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api_secret');
        if ($apiKey !== null) {
            $queryParams['api_secret'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation affiliatesContactsupdatedo
     *
     * Update
     *
     * @param  int $contactID contactID (required)
     * @param  string $firstName firstName (optional)
     * @param  string $lastName lastName (optional)
     * @param  string $jobTitle jobTitle (optional)
     * @param  string $emailAddress emailAddress (optional)
     * @param  string $phoneNumber phoneNumber (optional)
     * @param  string $officePhone officePhone (optional)
     * @param  string $ext ext (optional)
     * @param  string $portalAccess portalAccess (optional)
     * @param  string $role role (optional)
     * @param  string $massEmail massEmail (optional)
     * @param  string $permissionAccount permissionAccount (optional)
     * @param  string $permissionBilling permissionBilling (optional)
     * @param  string $permissionOffers permissionOffers (optional)
     * @param  string $permissionReports permissionReports (optional)
     * @param  string $permissionUsers permissionUsers (optional)
     *
     * @throws \Leadspedia\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function affiliatesContactsupdatedo($contactID, $firstName = null, $lastName = null, $jobTitle = null, $emailAddress = null, $phoneNumber = null, $officePhone = null, $ext = null, $portalAccess = null, $role = null, $massEmail = null, $permissionAccount = null, $permissionBilling = null, $permissionOffers = null, $permissionReports = null, $permissionUsers = null): void
    {
        $this->affiliatesContactsupdatedoWithHttpInfo($contactID, $firstName, $lastName, $jobTitle, $emailAddress, $phoneNumber, $officePhone, $ext, $portalAccess, $role, $massEmail, $permissionAccount, $permissionBilling, $permissionOffers, $permissionReports, $permissionUsers);
    }

    /**
     * Operation affiliatesContactsupdatedoWithHttpInfo
     *
     * Update
     *
     * @param  int $contactID (required)
     * @param  string $firstName (optional)
     * @param  string $lastName (optional)
     * @param  string $jobTitle (optional)
     * @param  string $emailAddress (optional)
     * @param  string $phoneNumber (optional)
     * @param  string $officePhone (optional)
     * @param  string $ext (optional)
     * @param  string $portalAccess (optional)
     * @param  string $role (optional)
     * @param  string $massEmail (optional)
     * @param  string $permissionAccount (optional)
     * @param  string $permissionBilling (optional)
     * @param  string $permissionOffers (optional)
     * @param  string $permissionReports (optional)
     * @param  string $permissionUsers (optional)
     *
     * @throws \Leadspedia\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function affiliatesContactsupdatedoWithHttpInfo($contactID, $firstName = null, $lastName = null, $jobTitle = null, $emailAddress = null, $phoneNumber = null, $officePhone = null, $ext = null, $portalAccess = null, $role = null, $massEmail = null, $permissionAccount = null, $permissionBilling = null, $permissionOffers = null, $permissionReports = null, $permissionUsers = null)
    {
        $request = $this->affiliatesContactsupdatedoRequest($contactID, $firstName, $lastName, $jobTitle, $emailAddress, $phoneNumber, $officePhone, $ext, $portalAccess, $role, $massEmail, $permissionAccount, $permissionBilling, $permissionOffers, $permissionReports, $permissionUsers);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation affiliatesContactsupdatedoAsync
     *
     * Update
     *
     * @param  int $contactID (required)
     * @param  string $firstName (optional)
     * @param  string $lastName (optional)
     * @param  string $jobTitle (optional)
     * @param  string $emailAddress (optional)
     * @param  string $phoneNumber (optional)
     * @param  string $officePhone (optional)
     * @param  string $ext (optional)
     * @param  string $portalAccess (optional)
     * @param  string $role (optional)
     * @param  string $massEmail (optional)
     * @param  string $permissionAccount (optional)
     * @param  string $permissionBilling (optional)
     * @param  string $permissionOffers (optional)
     * @param  string $permissionReports (optional)
     * @param  string $permissionUsers (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function affiliatesContactsupdatedoAsync($contactID, $firstName = null, $lastName = null, $jobTitle = null, $emailAddress = null, $phoneNumber = null, $officePhone = null, $ext = null, $portalAccess = null, $role = null, $massEmail = null, $permissionAccount = null, $permissionBilling = null, $permissionOffers = null, $permissionReports = null, $permissionUsers = null)
    {
        return $this->affiliatesContactsupdatedoAsyncWithHttpInfo($contactID, $firstName, $lastName, $jobTitle, $emailAddress, $phoneNumber, $officePhone, $ext, $portalAccess, $role, $massEmail, $permissionAccount, $permissionBilling, $permissionOffers, $permissionReports, $permissionUsers)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation affiliatesContactsupdatedoAsyncWithHttpInfo
     *
     * Update
     *
     * @param  int $contactID (required)
     * @param  string $firstName (optional)
     * @param  string $lastName (optional)
     * @param  string $jobTitle (optional)
     * @param  string $emailAddress (optional)
     * @param  string $phoneNumber (optional)
     * @param  string $officePhone (optional)
     * @param  string $ext (optional)
     * @param  string $portalAccess (optional)
     * @param  string $role (optional)
     * @param  string $massEmail (optional)
     * @param  string $permissionAccount (optional)
     * @param  string $permissionBilling (optional)
     * @param  string $permissionOffers (optional)
     * @param  string $permissionReports (optional)
     * @param  string $permissionUsers (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function affiliatesContactsupdatedoAsyncWithHttpInfo($contactID, $firstName = null, $lastName = null, $jobTitle = null, $emailAddress = null, $phoneNumber = null, $officePhone = null, $ext = null, $portalAccess = null, $role = null, $massEmail = null, $permissionAccount = null, $permissionBilling = null, $permissionOffers = null, $permissionReports = null, $permissionUsers = null)
    {
        $returnType = '';
        $request    = $this->affiliatesContactsupdatedoRequest($contactID, $firstName, $lastName, $jobTitle, $emailAddress, $phoneNumber, $officePhone, $ext, $portalAccess, $role, $massEmail, $permissionAccount, $permissionBilling, $permissionOffers, $permissionReports, $permissionUsers);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception): void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'affiliatesContactsupdatedo'
     *
     * @param  int $contactID (required)
     * @param  string $firstName (optional)
     * @param  string $lastName (optional)
     * @param  string $jobTitle (optional)
     * @param  string $emailAddress (optional)
     * @param  string $phoneNumber (optional)
     * @param  string $officePhone (optional)
     * @param  string $ext (optional)
     * @param  string $portalAccess (optional)
     * @param  string $role (optional)
     * @param  string $massEmail (optional)
     * @param  string $permissionAccount (optional)
     * @param  string $permissionBilling (optional)
     * @param  string $permissionOffers (optional)
     * @param  string $permissionReports (optional)
     * @param  string $permissionUsers (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function affiliatesContactsupdatedoRequest($contactID, $firstName = null, $lastName = null, $jobTitle = null, $emailAddress = null, $phoneNumber = null, $officePhone = null, $ext = null, $portalAccess = null, $role = null, $massEmail = null, $permissionAccount = null, $permissionBilling = null, $permissionOffers = null, $permissionReports = null, $permissionUsers = null)
    {
        // verify the required parameter 'contactID' is set
        if ($contactID === null || (is_array($contactID) && count($contactID) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $contactID when calling affiliatesContactsupdatedo'
            );
        }

        $resourcePath = '/affiliatesContacts/update.do';
        $formParams   = [];
        $queryParams  = [];
        $headerParams = [];
        $httpBody     = '';
        $multipart    = false;

        // query params
        if ($contactID !== null) {
            $queryParams['contactID'] = ObjectSerializer::toQueryValue($contactID);
        }
        // query params
        if ($firstName !== null) {
            $queryParams['firstName'] = ObjectSerializer::toQueryValue($firstName);
        }
        // query params
        if ($lastName !== null) {
            $queryParams['lastName'] = ObjectSerializer::toQueryValue($lastName);
        }
        // query params
        if ($jobTitle !== null) {
            $queryParams['jobTitle'] = ObjectSerializer::toQueryValue($jobTitle);
        }
        // query params
        if ($emailAddress !== null) {
            $queryParams['emailAddress'] = ObjectSerializer::toQueryValue($emailAddress);
        }
        // query params
        if ($phoneNumber !== null) {
            $queryParams['phoneNumber'] = ObjectSerializer::toQueryValue($phoneNumber);
        }
        // query params
        if ($officePhone !== null) {
            $queryParams['officePhone'] = ObjectSerializer::toQueryValue($officePhone);
        }
        // query params
        if ($ext !== null) {
            $queryParams['ext'] = ObjectSerializer::toQueryValue($ext);
        }
        // query params
        if ($portalAccess !== null) {
            $queryParams['portalAccess'] = ObjectSerializer::toQueryValue($portalAccess);
        }
        // query params
        if ($role !== null) {
            $queryParams['role'] = ObjectSerializer::toQueryValue($role);
        }
        // query params
        if ($massEmail !== null) {
            $queryParams['massEmail'] = ObjectSerializer::toQueryValue($massEmail);
        }
        // query params
        if ($permissionAccount !== null) {
            $queryParams['permission_account'] = ObjectSerializer::toQueryValue($permissionAccount);
        }
        // query params
        if ($permissionBilling !== null) {
            $queryParams['permission_billing'] = ObjectSerializer::toQueryValue($permissionBilling);
        }
        // query params
        if ($permissionOffers !== null) {
            $queryParams['permission_offers'] = ObjectSerializer::toQueryValue($permissionOffers);
        }
        // query params
        if ($permissionReports !== null) {
            $queryParams['permission_reports'] = ObjectSerializer::toQueryValue($permissionReports);
        }
        // query params
        if ($permissionUsers !== null) {
            $queryParams['permission_users'] = ObjectSerializer::toQueryValue($permissionUsers);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name'     => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api_key');
        if ($apiKey !== null) {
            $queryParams['api_key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api_secret');
        if ($apiKey !== null) {
            $queryParams['api_secret'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation affiliatesContactsverifyCredentialsdo
     *
     * Verify Credentials
     *
     * @param  string $emailAddress emailAddress (required)
     * @param  string $password password (required)
     *
     * @throws \Leadspedia\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function affiliatesContactsverifyCredentialsdo($emailAddress, $password): void
    {
        $this->affiliatesContactsverifyCredentialsdoWithHttpInfo($emailAddress, $password);
    }

    /**
     * Operation affiliatesContactsverifyCredentialsdoWithHttpInfo
     *
     * Verify Credentials
     *
     * @param  string $emailAddress (required)
     * @param  string $password (required)
     *
     * @throws \Leadspedia\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function affiliatesContactsverifyCredentialsdoWithHttpInfo($emailAddress, $password)
    {
        $request = $this->affiliatesContactsverifyCredentialsdoRequest($emailAddress, $password);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation affiliatesContactsverifyCredentialsdoAsync
     *
     * Verify Credentials
     *
     * @param  string $emailAddress (required)
     * @param  string $password (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function affiliatesContactsverifyCredentialsdoAsync($emailAddress, $password)
    {
        return $this->affiliatesContactsverifyCredentialsdoAsyncWithHttpInfo($emailAddress, $password)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation affiliatesContactsverifyCredentialsdoAsyncWithHttpInfo
     *
     * Verify Credentials
     *
     * @param  string $emailAddress (required)
     * @param  string $password (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function affiliatesContactsverifyCredentialsdoAsyncWithHttpInfo($emailAddress, $password)
    {
        $returnType = '';
        $request    = $this->affiliatesContactsverifyCredentialsdoRequest($emailAddress, $password);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception): void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'affiliatesContactsverifyCredentialsdo'
     *
     * @param  string $emailAddress (required)
     * @param  string $password (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function affiliatesContactsverifyCredentialsdoRequest($emailAddress, $password)
    {
        // verify the required parameter 'emailAddress' is set
        if ($emailAddress === null || (is_array($emailAddress) && count($emailAddress) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $emailAddress when calling affiliatesContactsverifyCredentialsdo'
            );
        }
        // verify the required parameter 'password' is set
        if ($password === null || (is_array($password) && count($password) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $password when calling affiliatesContactsverifyCredentialsdo'
            );
        }

        $resourcePath = '/affiliatesContacts/verifyCredentials.do';
        $formParams   = [];
        $queryParams  = [];
        $headerParams = [];
        $httpBody     = '';
        $multipart    = false;

        // query params
        if ($emailAddress !== null) {
            $queryParams['emailAddress'] = ObjectSerializer::toQueryValue($emailAddress);
        }
        // query params
        if ($password !== null) {
            $queryParams['password'] = ObjectSerializer::toQueryValue($password);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name'     => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api_key');
        if ($apiKey !== null) {
            $queryParams['api_key'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api_secret');
        if ($apiKey !== null) {
            $queryParams['api_secret'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
