<?php
/**
 * AdvertisersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  LeadspediaApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * LeadsPedia API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.10
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace LeadspediaApi;

use LeadspediaApi\Configuration;
use LeadspediaApi\ApiException;
use LeadspediaApi\ObjectSerializer;

/**
 * AdvertisersApiTest Class Doc Comment
 *
 * @category Class
 * @package  LeadspediaApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AdvertisersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for advertisersadjustCreditdo
     *
     * Adjust Credit.
     *
     */
    public function testAdvertisersadjustCreditdo()
    {
    }

    /**
     * Test case for advertiserschangeStatusdo
     *
     * Change Status.
     *
     */
    public function testAdvertiserschangeStatusdo()
    {
    }

    /**
     * Test case for advertiserscreatedo
     *
     * Create.
     *
     */
    public function testAdvertiserscreatedo()
    {
    }

    /**
     * Test case for advertisersdeletedo
     *
     * Delete.
     *
     */
    public function testAdvertisersdeletedo()
    {
    }

    /**
     * Test case for advertisersenableCreditdo
     *
     * Enable Credit.
     *
     */
    public function testAdvertisersenableCreditdo()
    {
    }

    /**
     * Test case for advertisersgetAlldo
     *
     * Get All.
     *
     */
    public function testAdvertisersgetAlldo()
    {
    }

    /**
     * Test case for advertisersgetInfodo
     *
     * Get Info.
     *
     */
    public function testAdvertisersgetInfodo()
    {
    }

    /**
     * Test case for advertiserssearchdo
     *
     * Search.
     *
     */
    public function testAdvertiserssearchdo()
    {
    }

    /**
     * Test case for advertisersupdateAuthorizeNetCustomerProfileIDdo
     *
     * Update Authorize Net Customer Profile ID.
     *
     */
    public function testAdvertisersupdateAuthorizeNetCustomerProfileIDdo()
    {
    }

    /**
     * Test case for advertisersupdateAutoRechargeSettingsdo
     *
     * Update Auto Recharge Settings.
     *
     */
    public function testAdvertisersupdateAutoRechargeSettingsdo()
    {
    }

    /**
     * Test case for advertisersupdateBillingdo
     *
     * Update Billing.
     *
     */
    public function testAdvertisersupdateBillingdo()
    {
    }

    /**
     * Test case for advertisersupdateInfodo
     *
     * Update Info.
     *
     */
    public function testAdvertisersupdateInfodo()
    {
    }

    /**
     * Test case for advertisersupdatePortalSettingsdo
     *
     * Update Portal Settings.
     *
     */
    public function testAdvertisersupdatePortalSettingsdo()
    {
    }
}
