<?php
/**
 * AdvertisersCreditCardsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Leadspedia
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LeadsPedia API Reference
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Leadspedia;

use PHPUnit\Framework\TestCase;

/**
 * AdvertisersCreditCardsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Leadspedia
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AdvertisersCreditCardsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for advertisersCreditCardsadddo
     *
     * Add.
     *
     */
    public function testAdvertisersCreditCardsadddo(): void
    {
    }

    /**
     * Test case for advertisersCreditCardsdeletedo
     *
     * Delete.
     *
     */
    public function testAdvertisersCreditCardsdeletedo(): void
    {
    }

    /**
     * Test case for advertisersCreditCardsgetAlldo
     *
     * Get All.
     *
     */
    public function testAdvertisersCreditCardsgetAlldo(): void
    {
    }

    /**
     * Test case for advertisersCreditCardsgetDefaultdo
     *
     * Get Default.
     *
     */
    public function testAdvertisersCreditCardsgetDefaultdo(): void
    {
    }

    /**
     * Test case for advertisersCreditCardsgetInfodo
     *
     * Get Info.
     *
     */
    public function testAdvertisersCreditCardsgetInfodo(): void
    {
    }

    /**
     * Test case for advertisersCreditCardssetDefaultdo
     *
     * Set Default.
     *
     */
    public function testAdvertisersCreditCardssetDefaultdo(): void
    {
    }

    /**
     * Test case for advertisersCreditCardsupdatePaymentProfileIDdo
     *
     * Update Payment Profile ID.
     *
     */
    public function testAdvertisersCreditCardsupdatePaymentProfileIDdo(): void
    {
    }

    /**
     * Test case for advertisersCreditCardsupdatedo
     *
     * Update.
     *
     */
    public function testAdvertisersCreditCardsupdatedo(): void
    {
    }
}
