<?php
/**
 * AdvertiserscontactsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  LeadspediaApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * LeadsPedia API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.10
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace LeadspediaApi;

use LeadspediaApi\Configuration;
use LeadspediaApi\ApiException;
use LeadspediaApi\ObjectSerializer;

/**
 * AdvertiserscontactsApiTest Class Doc Comment
 *
 * @category Class
 * @package  LeadspediaApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AdvertiserscontactsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for advertisersContactschangePassworddo
     *
     * Change Password.
     *
     */
    public function testAdvertisersContactschangePassworddo()
    {
    }

    /**
     * Test case for advertisersContactschangeStatusdo
     *
     * Change Status.
     *
     */
    public function testAdvertisersContactschangeStatusdo()
    {
    }

    /**
     * Test case for advertisersContactscreatedo
     *
     * Create.
     *
     */
    public function testAdvertisersContactscreatedo()
    {
    }

    /**
     * Test case for advertisersContactsdeletedo
     *
     * Delete.
     *
     */
    public function testAdvertisersContactsdeletedo()
    {
    }

    /**
     * Test case for advertisersContactsgetAlldo
     *
     * Get All.
     *
     */
    public function testAdvertisersContactsgetAlldo()
    {
    }

    /**
     * Test case for advertisersContactsgetInfodo
     *
     * Get Info.
     *
     */
    public function testAdvertisersContactsgetInfodo()
    {
    }

    /**
     * Test case for advertisersContactsupdatedo
     *
     * Update.
     *
     */
    public function testAdvertisersContactsupdatedo()
    {
    }

    /**
     * Test case for advertisersContactsverifyCredentialsdo
     *
     * Verify Credentials.
     *
     */
    public function testAdvertisersContactsverifyCredentialsdo()
    {
    }
}
