<?php
/**
 * AdvertisersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Leadspedia
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LeadsPedia API Reference
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Leadspedia;

use PHPUnit\Framework\TestCase;

/**
 * AdvertisersApiTest Class Doc Comment
 *
 * @category Class
 * @package  Leadspedia
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AdvertisersApiTest extends TestCase
{
    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Test case for advertisersadjustCreditdo
     *
     * Adjust Credit.
     *
     */
    public function testAdvertisersadjustCreditdo(): void
    {
    }

    /**
     * Test case for advertiserschangeStatusdo
     *
     * Change Status.
     *
     */
    public function testAdvertiserschangeStatusdo(): void
    {
    }

    /**
     * Test case for advertiserscreatedo
     *
     * Create.
     *
     */
    public function testAdvertiserscreatedo(): void
    {
    }

    /**
     * Test case for advertisersdeletedo
     *
     * Delete.
     *
     */
    public function testAdvertisersdeletedo(): void
    {
    }

    /**
     * Test case for advertisersenableCreditdo
     *
     * Enable Credit.
     *
     */
    public function testAdvertisersenableCreditdo(): void
    {
    }

    /**
     * Test case for advertisersgetAlldo
     *
     * Get All.
     *
     */
    public function testAdvertisersgetAlldo(): void
    {
    }

    /**
     * Test case for advertisersgetInfodo
     *
     * Get Info.
     *
     */
    public function testAdvertisersgetInfodo(): void
    {
    }

    /**
     * Test case for advertiserssearchdo
     *
     * Search.
     *
     */
    public function testAdvertiserssearchdo(): void
    {
    }

    /**
     * Test case for advertisersupdateAuthorizeNetCustomerProfileIDdo
     *
     * Update Authorize Net Customer Profile ID.
     *
     */
    public function testAdvertisersupdateAuthorizeNetCustomerProfileIDdo(): void
    {
    }

    /**
     * Test case for advertisersupdateAutoRechargeSettingsdo
     *
     * Update Auto Recharge Settings.
     *
     */
    public function testAdvertisersupdateAutoRechargeSettingsdo(): void
    {
    }

    /**
     * Test case for advertisersupdateBillingdo
     *
     * Update Billing.
     *
     */
    public function testAdvertisersupdateBillingdo(): void
    {
    }

    /**
     * Test case for advertisersupdateInfodo
     *
     * Update Info.
     *
     */
    public function testAdvertisersupdateInfodo(): void
    {
    }

    /**
     * Test case for advertisersupdateLeadsCapsdo
     *
     * Update Leads Caps.
     *
     */
    public function testAdvertisersupdateLeadsCapsdo(): void
    {
    }

    /**
     * Test case for advertisersupdateLeadsDailyCapdo
     *
     * Update Leads Daily Cap.
     *
     */
    public function testAdvertisersupdateLeadsDailyCapdo(): void
    {
    }

    /**
     * Test case for advertisersupdateLeadsDailyRevenueCapdo
     *
     * Update Leads Daily Revenue Cap.
     *
     */
    public function testAdvertisersupdateLeadsDailyRevenueCapdo(): void
    {
    }

    /**
     * Test case for advertisersupdateLeadsMonthlyCapdo
     *
     * Update Leads Monthly Cap.
     *
     */
    public function testAdvertisersupdateLeadsMonthlyCapdo(): void
    {
    }

    /**
     * Test case for advertisersupdateLeadsMonthlyRevenueCapdo
     *
     * Update Leads Monthly Revenue Cap.
     *
     */
    public function testAdvertisersupdateLeadsMonthlyRevenueCapdo(): void
    {
    }

    /**
     * Test case for advertisersupdateLeadsRevenueCapsdo
     *
     * Update Leads Revenue Caps.
     *
     */
    public function testAdvertisersupdateLeadsRevenueCapsdo(): void
    {
    }

    /**
     * Test case for advertisersupdateLeadsWeeklyCapdo
     *
     * Update Leads Weekly Cap.
     *
     */
    public function testAdvertisersupdateLeadsWeeklyCapdo(): void
    {
    }

    /**
     * Test case for advertisersupdateLeadsWeeklyRevenueCapdo
     *
     * Update Leads Weekly Revenue Cap.
     *
     */
    public function testAdvertisersupdateLeadsWeeklyRevenueCapdo(): void
    {
    }

    /**
     * Test case for advertisersupdatePortalSettingsdo
     *
     * Update Portal Settings.
     *
     */
    public function testAdvertisersupdatePortalSettingsdo(): void
    {
    }
}
