<?php
/**
 * AffiliatesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  LeadspediaApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * LeadsPedia API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.10
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace LeadspediaApi;

use LeadspediaApi\Configuration;
use LeadspediaApi\ApiException;
use LeadspediaApi\ObjectSerializer;

/**
 * AffiliatesApiTest Class Doc Comment
 *
 * @category Class
 * @package  LeadspediaApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AffiliatesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for affiliateschangeStatusdo
     *
     * Change Status.
     *
     */
    public function testAffiliateschangeStatusdo()
    {
    }

    /**
     * Test case for affiliatescreatedo
     *
     * Create.
     *
     */
    public function testAffiliatescreatedo()
    {
    }

    /**
     * Test case for affiliatesdeletedo
     *
     * Delete.
     *
     */
    public function testAffiliatesdeletedo()
    {
    }

    /**
     * Test case for affiliatesgetAlldo
     *
     * Get All.
     *
     */
    public function testAffiliatesgetAlldo()
    {
    }

    /**
     * Test case for affiliatesgetInfodo
     *
     * Get Info.
     *
     */
    public function testAffiliatesgetInfodo()
    {
    }

    /**
     * Test case for affiliatessearchdo
     *
     * Search.
     *
     */
    public function testAffiliatessearchdo()
    {
    }

    /**
     * Test case for affiliatesupdateBillingdo
     *
     * Update Billing.
     *
     */
    public function testAffiliatesupdateBillingdo()
    {
    }

    /**
     * Test case for affiliatesupdateInfodo
     *
     * Update Info.
     *
     */
    public function testAffiliatesupdateInfodo()
    {
    }
}
