<?php
/**
 * ConversionsReportsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Leadspedia
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LeadsPedia API Reference
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Leadspedia;

use PHPUnit\Framework\TestCase;

/**
 * ConversionsReportsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Leadspedia
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ConversionsReportsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for conversionsReportsgetConversionsByAdvertisersReportdo
     *
     * Get Conversions By Advertisers Report.
     *
     */
    public function testConversionsReportsgetConversionsByAdvertisersReportdo(): void
    {
    }

    /**
     * Test case for conversionsReportsgetConversionsByAffiliatesReportdo
     *
     * Get Conversions By Affiliates Report.
     *
     */
    public function testConversionsReportsgetConversionsByAffiliatesReportdo(): void
    {
    }

    /**
     * Test case for conversionsReportsgetConversionsByCampaignsReportdo
     *
     * Get Conversions By Campaigns Report.
     *
     */
    public function testConversionsReportsgetConversionsByCampaignsReportdo(): void
    {
    }

    /**
     * Test case for conversionsReportsgetConversionsByOffersReportdo
     *
     * Get Conversions By Offers Report.
     *
     */
    public function testConversionsReportsgetConversionsByOffersReportdo(): void
    {
    }

    /**
     * Test case for conversionsReportsgetConversionsBySourceReportdo
     *
     * Get Conversions By Source Report.
     *
     */
    public function testConversionsReportsgetConversionsBySourceReportdo(): void
    {
    }

    /**
     * Test case for conversionsReportsgetConversionsBySubAffiliatesReportdo
     *
     * Get Conversions By Sub Affiliates Report.
     *
     */
    public function testConversionsReportsgetConversionsBySubAffiliatesReportdo(): void
    {
    }

    /**
     * Test case for conversionsReportsgetConversionsByVerticalsReportdo
     *
     * Get Conversions By Verticals Report.
     *
     */
    public function testConversionsReportsgetConversionsByVerticalsReportdo(): void
    {
    }

    /**
     * Test case for conversionsReportsgetConversionsDailyReportdo
     *
     * Get Conversions Daily Report.
     *
     */
    public function testConversionsReportsgetConversionsDailyReportdo(): void
    {
    }
}
