<?php
/**
 * InboundcallsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  LeadspediaApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * LeadsPedia API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.10
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace LeadspediaApi;

use LeadspediaApi\Configuration;
use LeadspediaApi\ApiException;
use LeadspediaApi\ObjectSerializer;

/**
 * InboundcallsApiTest Class Doc Comment
 *
 * @category Class
 * @package  LeadspediaApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InboundcallsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for inboundCallsgetAlldo
     *
     * Get All.
     *
     */
    public function testInboundCallsgetAlldo()
    {
    }

    /**
     * Test case for inboundCallsgetInProgressdo
     *
     * Get Calls In Progress.
     *
     */
    public function testInboundCallsgetInProgressdo()
    {
    }

    /**
     * Test case for inboundCallsgetNumbersdo
     *
     * Get Numbers.
     *
     */
    public function testInboundCallsgetNumbersdo()
    {
    }

    /**
     * Test case for inboundCallsgetReturneddo
     *
     * Get Returned Calls.
     *
     */
    public function testInboundCallsgetReturneddo()
    {
    }

    /**
     * Test case for inboundCallsgetScrubbeddo
     *
     * Get Scrubbed Calls.
     *
     */
    public function testInboundCallsgetScrubbeddo()
    {
    }

    /**
     * Test case for inboundCallsgetTransferreddo
     *
     * Get Transferred Calls.
     *
     */
    public function testInboundCallsgetTransferreddo()
    {
    }
}
