<?php
/**
 * LeadsReportsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Leadspedia
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LeadsPedia API Reference
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Leadspedia;

use PHPUnit\Framework\TestCase;

/**
 * LeadsReportsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Leadspedia
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LeadsReportsApiTest extends TestCase
{
    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Test case for leadsReportsgetCampaignsLeadsCapReportdo
     *
     * Get Campaigns Leads Cap Report.
     *
     */
    public function testLeadsReportsgetCampaignsLeadsCapReportdo(): void
    {
    }

    /**
     * Test case for leadsReportsgetCampaignsLeadsFieldsCapReportdo
     *
     * Get Campaigns Leads Fields Cap Report.
     *
     */
    public function testLeadsReportsgetCampaignsLeadsFieldsCapReportdo(): void
    {
    }

    /**
     * Test case for leadsReportsgetContractsLeadsCapReportdo
     *
     * Get Contracts Leads Cap Report.
     *
     */
    public function testLeadsReportsgetContractsLeadsCapReportdo(): void
    {
    }

    /**
     * Test case for leadsReportsgetContractsLeadsFieldsCapReportdo
     *
     * Get Contracts Leads Fields Cap Report.
     *
     */
    public function testLeadsReportsgetContractsLeadsFieldsCapReportdo(): void
    {
    }

    /**
     * Test case for leadsReportsgetLeadDistributionReportdo
     *
     * Get Lead Distribution Report.
     *
     */
    public function testLeadsReportsgetLeadDistributionReportdo(): void
    {
    }

    /**
     * Test case for leadsReportsgetLeadsByAdvertisersDailyReportdo
     *
     * Get Leads By Advertisers Daily Report.
     *
     */
    public function testLeadsReportsgetLeadsByAdvertisersDailyReportdo(): void
    {
    }

    /**
     * Test case for leadsReportsgetLeadsByAdvertisersReportdo
     *
     * Get Leads By Advertisers Report.
     *
     */
    public function testLeadsReportsgetLeadsByAdvertisersReportdo(): void
    {
    }

    /**
     * Test case for leadsReportsgetLeadsByAffiliatesDailyReportdo
     *
     * Get Leads By Affiliates Daily Report.
     *
     */
    public function testLeadsReportsgetLeadsByAffiliatesDailyReportdo(): void
    {
    }

    /**
     * Test case for leadsReportsgetLeadsByAffiliatesReportdo
     *
     * Get Leads By Affiliates Report.
     *
     */
    public function testLeadsReportsgetLeadsByAffiliatesReportdo(): void
    {
    }

    /**
     * Test case for leadsReportsgetLeadsByCampaignsReportdo
     *
     * Get Leads By Campaigns Report.
     *
     */
    public function testLeadsReportsgetLeadsByCampaignsReportdo(): void
    {
    }

    /**
     * Test case for leadsReportsgetLeadsByContractsReportdo
     *
     * Get Leads By Contracts Report.
     *
     */
    public function testLeadsReportsgetLeadsByContractsReportdo(): void
    {
    }

    /**
     * Test case for leadsReportsgetLeadsByOffersReportdo
     *
     * Get Leads By Offers Report.
     *
     */
    public function testLeadsReportsgetLeadsByOffersReportdo(): void
    {
    }

    /**
     * Test case for leadsReportsgetLeadsBySubAffiliatesReportdo
     *
     * Get Leads By Sub Affiliates Report.
     *
     */
    public function testLeadsReportsgetLeadsBySubAffiliatesReportdo(): void
    {
    }

    /**
     * Test case for leadsReportsgetLeadsByVerticalsReportdo
     *
     * Get Leads By Verticals Report.
     *
     */
    public function testLeadsReportsgetLeadsByVerticalsReportdo(): void
    {
    }

    /**
     * Test case for leadsReportsgetOffersLeadsCapReportdo
     *
     * Get Offers Leads Cap Report.
     *
     */
    public function testLeadsReportsgetOffersLeadsCapReportdo(): void
    {
    }

    /**
     * Test case for leadsReportsgetPingPostReportdo
     *
     * Get Ping Post Report.
     *
     */
    public function testLeadsReportsgetPingPostReportdo(): void
    {
    }
}
